# Generated by Django 2.0 on 2018-01-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-add_time',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-heat',)},
        ),
    ]
