# Generated by Django 2.0 on 2018-01-02 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_created=True)),
                ('has_read', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='QA.Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='QA.Question')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtar', models.ImageField(default='', upload_to='')),
                ('nickname', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('agreed', models.ManyToManyField(related_name='agreedUser', to='QA.Answer')),
                ('disagreed', models.ManyToManyField(related_name='disagreedUser', to='QA.Answer')),
                ('favorites', models.ManyToManyField(to='QA.Answer')),
                ('history', models.ManyToManyField(related_name='history', to='QA.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchedQuestion', models.ManyToManyField(related_name='watchedUser', to='QA.Question')),
                ('watchedUser', models.ManyToManyField(related_name='_profile_watchedUser_+', to='accounts.Profile')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
