# Generated by Django 2.0 on 2017-12-23 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agreed',
            field=models.ManyToManyField(related_name='agreedUser', to='QA.Answer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disagreed',
            field=models.ManyToManyField(related_name='disagreedUser', to='QA.Answer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(related_name='history', to='QA.Question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchedQuestion',
            field=models.ManyToManyField(related_name='watchedUser', to='QA.Question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchedUser',
            field=models.ManyToManyField(related_name='WatchedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
