# Generated by Django 2.0 on 2017-12-23 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watched_user',
            field=models.ManyToManyField(blank=True, related_name='been_watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
